# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/gitaar_effect/ip/ip.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0.xci
# IP: The module: 'clk_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/gitaar_effect/ip/ip.srcs/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0.xci
# IP: The module: 'clk_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
