# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.srcs/sources_1/bd/fifo/ip/fifo_fifo_generator_0_0_1/fifo_fifo_generator_0_0.xci
# IP: The module: 'fifo_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/fifo/ip/fifo_fifo_generator_0_0_1/fifo_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/fifo/ip/fifo_fifo_generator_0_0_1/fifo_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.srcs/sources_1/bd/fifo/ip/fifo_fifo_generator_0_0_1/fifo_fifo_generator_0_0.xci
# IP: The module: 'fifo_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/fifo/ip/fifo_fifo_generator_0_0_1/fifo_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/fifo/ip/fifo_fifo_generator_0_0_1/fifo_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
