# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.srcs/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/effects_pedal_chorus_pedal_0_0.xci
# IP: The module: 'effects_pedal_chorus_pedal_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/chorus_pedal_Chorus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_pedal_Chorus_0_0 || ORIG_REF_NAME==chorus_pedal_Chorus_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_blk_mem_gen_0_0 || ORIG_REF_NAME==Chorus_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_c_addsub_0_0/Chorus_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_c_addsub_0_0 || ORIG_REF_NAME==Chorus_c_addsub_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_chorus_mem_driver_ip_0_0/Chorus_chorus_mem_driver_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_chorus_mem_driver_ip_0_0 || ORIG_REF_NAME==Chorus_chorus_mem_driver_ip_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/chorus_pedal_Chorus_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_pedal_Chorus_0_1 || ORIG_REF_NAME==chorus_pedal_Chorus_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_blk_mem_gen_0_0 || ORIG_REF_NAME==Chorus_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_c_addsub_0_0/Chorus_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_c_addsub_0_0 || ORIG_REF_NAME==Chorus_c_addsub_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_chorus_mem_driver_ip_0_0/Chorus_chorus_mem_driver_ip_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_chorus_mem_driver_ip_0_0 || ORIG_REF_NAME==Chorus_chorus_mem_driver_ip_0_0} -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_chorus_mem_driver_ip_0_0/src/chorus_mem_driver_ip_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_chorus_mem_driver_ip_0_0/src/chorus_mem_driver_ip_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'effects_pedal_chorus_pedal_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.srcs/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/effects_pedal_chorus_pedal_0_0.xci
# IP: The module: 'effects_pedal_chorus_pedal_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/chorus_pedal_Chorus_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_pedal_Chorus_0_0 || ORIG_REF_NAME==chorus_pedal_Chorus_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_blk_mem_gen_0_0 || ORIG_REF_NAME==Chorus_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_c_addsub_0_0/Chorus_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_c_addsub_0_0 || ORIG_REF_NAME==Chorus_c_addsub_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_chorus_mem_driver_ip_0_0/Chorus_chorus_mem_driver_ip_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_chorus_mem_driver_ip_0_0 || ORIG_REF_NAME==Chorus_chorus_mem_driver_ip_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/chorus_pedal_Chorus_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_pedal_Chorus_0_1 || ORIG_REF_NAME==chorus_pedal_Chorus_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_blk_mem_gen_0_0 || ORIG_REF_NAME==Chorus_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_c_addsub_0_0/Chorus_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_c_addsub_0_0 || ORIG_REF_NAME==Chorus_c_addsub_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_chorus_mem_driver_ip_0_0/Chorus_chorus_mem_driver_ip_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Chorus_chorus_mem_driver_ip_0_0 || ORIG_REF_NAME==Chorus_chorus_mem_driver_ip_0_0} -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_chorus_mem_driver_ip_0_0/src/chorus_mem_driver_ip_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_0/src/Chorus_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_blk_mem_gen_0_0/Chorus_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_chorus_mem_driver_ip_0_0/src/chorus_mem_driver_ip_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_Chorus_0_1/src/Chorus_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/src/chorus_pedal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'effects_pedal_chorus_pedal_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
