# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/bd/delay_channel_1_inst_2/ip/delay_channel_1_inst_2_fir_compiler_0_0/delay_channel_1_inst_2_fir_compiler_0_0.xci
# IP: The module: 'delay_channel_1_inst_2_fir_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/bd/delay_channel_1_inst_2/ip/delay_channel_1_inst_2_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_channel_1_inst_2_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/bd/delay_channel_1_inst_2/ip/delay_channel_1_inst_2_fir_compiler_0_0/delay_channel_1_inst_2_fir_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_channel_1_inst_2_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/bd/delay_channel_1_inst_2/ip/delay_channel_1_inst_2_fir_compiler_0_0/delay_channel_1_inst_2_fir_compiler_0_0.xci
# IP: The module: 'delay_channel_1_inst_2_fir_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/bd/delay_channel_1_inst_2/ip/delay_channel_1_inst_2_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_channel_1_inst_2_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/bd/delay_channel_1_inst_2/ip/delay_channel_1_inst_2_fir_compiler_0_0/delay_channel_1_inst_2_fir_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delay_channel_1_inst_2_fir_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
