# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/gitaar_effect/ip/ip.srcs/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/effects_pedal_chorus_0_1.xci
# IP: The module: 'effects_pedal_chorus_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_0/chorus_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_blk_mem_gen_0_0 || ORIG_REF_NAME==chorus_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_c_addsub_0_0/chorus_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_c_addsub_0_0 || ORIG_REF_NAME==chorus_c_addsub_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_1/chorus_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_blk_mem_gen_0_1 || ORIG_REF_NAME==chorus_blk_mem_gen_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_c_addsub_0_1/chorus_c_addsub_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_c_addsub_0_1 || ORIG_REF_NAME==chorus_c_addsub_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_util_vector_logic_0_1/chorus_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_util_vector_logic_0_1 || ORIG_REF_NAME==chorus_util_vector_logic_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_util_vector_logic_0_2/chorus_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_util_vector_logic_0_2 || ORIG_REF_NAME==chorus_util_vector_logic_0_2} -quiet] -quiet

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_0/chorus_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_1/chorus_blk_mem_gen_0_1_ooc.xdc

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'effects_pedal_chorus_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.srcs/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/effects_pedal_chorus_0_1.xci
# IP: The module: 'effects_pedal_chorus_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_0/chorus_blk_mem_gen_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_blk_mem_gen_0_0 || ORIG_REF_NAME==chorus_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_c_addsub_0_0/chorus_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_c_addsub_0_0 || ORIG_REF_NAME==chorus_c_addsub_0_0} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_1/chorus_blk_mem_gen_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_blk_mem_gen_0_1 || ORIG_REF_NAME==chorus_blk_mem_gen_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_c_addsub_0_1/chorus_c_addsub_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_c_addsub_0_1 || ORIG_REF_NAME==chorus_c_addsub_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_util_vector_logic_0_1/chorus_util_vector_logic_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_util_vector_logic_0_1 || ORIG_REF_NAME==chorus_util_vector_logic_0_1} -quiet] -quiet

# IP: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_util_vector_logic_0_2/chorus_util_vector_logic_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chorus_util_vector_logic_0_2 || ORIG_REF_NAME==chorus_util_vector_logic_0_2} -quiet] -quiet

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_0/chorus_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_blk_mem_gen_0_1/chorus_blk_mem_gen_0_1_ooc.xdc

# XDC: c:/gitaar_effect/ip/ip.gen/sources_1/bd/effects_pedal/ip/effects_pedal_chorus_0_1/src/chorus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'effects_pedal_chorus_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
