# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-A7-100T-Master.xdc

# Block Designs: bd/clk/clk.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk || ORIG_REF_NAME==clk} -quiet] -quiet

# IP: bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_clk_wiz_0_0 || ORIG_REF_NAME==clk_clk_wiz_0_0} -quiet] -quiet

# Block Designs: bd/effects_pedal/effects_pedal.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==effects_pedal || ORIG_REF_NAME==effects_pedal} -quiet] -quiet

# IP: bd/effects_pedal/ip/effects_pedal_chorus_pedal_0_0/effects_pedal_chorus_pedal_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==effects_pedal_chorus_pedal_0_0 || ORIG_REF_NAME==effects_pedal_chorus_pedal_0_0} -quiet] -quiet

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/clk/clk_ooc.xdc

# XDC: c:/gitaar_effect/Gitaar_effect_delay/Gitaar_effect_delay.gen/sources_1/bd/effects_pedal/effects_pedal_ooc.xdc
